# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sukko < Formula
  desc "Sukko WebSocket platform CLI"
  homepage "https://github.com/klurvio/sukko-cli"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/klurvio/sukko-cli/releases/download/v0.4.0/sukko_0.4.0_darwin_amd64.tar.gz"
      sha256 "f9a258701fef5a2bdff6cb002844f8da5cc4e39a68c16a44a0e06920a98729be"

      define_method(:install) do
        bin.install "sukko"
        generate_completions_from_executable(bin/"sukko", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/klurvio/sukko-cli/releases/download/v0.4.0/sukko_0.4.0_darwin_arm64.tar.gz"
      sha256 "22b73c891d3f1269adb54f49a2d565f2a13c11f94a956d1ea4e433085b69eaa6"

      define_method(:install) do
        bin.install "sukko"
        generate_completions_from_executable(bin/"sukko", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/klurvio/sukko-cli/releases/download/v0.4.0/sukko_0.4.0_linux_amd64.tar.gz"
      sha256 "e9361514e43cf6cdfa0239ddcb0a69179444844c63c5403d5c0374198274589f"
      define_method(:install) do
        bin.install "sukko"
        generate_completions_from_executable(bin/"sukko", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/klurvio/sukko-cli/releases/download/v0.4.0/sukko_0.4.0_linux_arm64.tar.gz"
      sha256 "e754df29ec0efbdcdff163a8dd7811623622de144b0da773b357c4723283d4ba"
      define_method(:install) do
        bin.install "sukko"
        generate_completions_from_executable(bin/"sukko", "completion")
      end
    end
  end

  test do
    system "#{bin}/sukko", "version"
  end
end
