# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sukko < Formula
  desc "Sukko WebSocket platform CLI"
  homepage "https://github.com/klurvio/sukko-cli"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/klurvio/sukko-cli/releases/download/v0.2.1/sukko_0.2.1_darwin_amd64.tar.gz"
      sha256 "812810e83fca02c904c023391edf89e4806af17f2ebe16a0704835be6e5c166a"

      define_method(:install) do
        bin.install "sukko"
        generate_completions_from_executable(bin/"sukko", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/klurvio/sukko-cli/releases/download/v0.2.1/sukko_0.2.1_darwin_arm64.tar.gz"
      sha256 "7615d599799d5c3a097ff01afcab22cd86cfdb31a95e708e7eb49b059f8b55a2"

      define_method(:install) do
        bin.install "sukko"
        generate_completions_from_executable(bin/"sukko", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/klurvio/sukko-cli/releases/download/v0.2.1/sukko_0.2.1_linux_amd64.tar.gz"
      sha256 "f7b11d5352bc57ee1d0fd6078b6d69c57f894e41491e4008e856782543f31fa3"
      define_method(:install) do
        bin.install "sukko"
        generate_completions_from_executable(bin/"sukko", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/klurvio/sukko-cli/releases/download/v0.2.1/sukko_0.2.1_linux_arm64.tar.gz"
      sha256 "c942503549838df6453c4f4e11183de24b0d3458f2966c67d0146dde692873f8"
      define_method(:install) do
        bin.install "sukko"
        generate_completions_from_executable(bin/"sukko", "completion")
      end
    end
  end

  test do
    system "#{bin}/sukko", "version"
  end
end
